name: NeoInstantWarps
author: Neoblade298
main: me.neoblade298.neoinstantwarps.Main
depend: [Essentials]
version: 1.00
commands:
  iwarp:
    description: Does its job
    usage: /iwarp [warpname] [playername]